branches:
 except:
  - /appveyor/
language: perl
matrix:
  include:
    - perl: "5.14"
      env: USE_SYSTEM_PERL=1
    - perl: "5.20"
    - perl: "5.20"
      env: WITH_OPTIONAL_MODULES=1
    - perl: "5.18"
    - perl: "5.16"
    - perl: "5.14"
    - perl: "5.12"
    - perl: "5.10"
    - perl: "5.8"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && perlbrew off || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && sudo apt-get install -qq libx11-dev libfreetype6-dev libxft-dev || true'
 - Xvfb :123 &
 - export DISPLAY=:123
 - (sleep 10; twm) &
install:
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq perl-tk || true'
## XXX Tk + EUMM 7.00 problems, use the current development version (https://rt.cpan.org/Ticket/Display.html?id=100044)
# - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest SREZIC/Tk-804.032_501.tar.gz || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest --installdeps . || true'
# XXX would be nice to use cpanm's --with-all-features, but have to be checked first
# XXX PerlIO::gzip is missing --- it's known to be broken with latest perls, see https://rt.cpan.org/Ticket/Display.html?id=92412
 - '[ "$WITH_OPTIONAL_MODULES" = "1" ] && cpanm --quiet --notest Text::English Tk::HistEntry Tk::ToolBar Tk::WidgetDump Module::Refresh Devel::Hide URI::Escape || true'
