branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - set PROJECTNAME=tk-pod
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%PROJECTNAME%
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
  - dmake test
