meta-spec:
    version: 1.3
    url: http://module-build.sourceforge.net/META-spec-v1.3.html
name:         Tk-Pod
version:      0.9939_57
abstract: Pod browser widget for Tk
author:
    - Slaven Rezic <srezic@cpan.org>
requires:
    File::Temp:                    0
    Pod::Simple:                   0
    Tk:                            800.004
optional_features:
    fulltext_search:
        description: "Enable the full-text search"
        requires:
            Text::English:                 0
    nicer_gui:
        description: "Provide a nicer GUI"
        requires:
            Tk::HistEntry:                 0.4
            Tk::ToolBar:                   0
    debugging:
        description: "Debugging helper"
        requires:
            Tk::WidgetDump:                0
            Module:Refresh:                0
dynamic_config: 0
license: perl
distribution_type: module
resources:
    bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Tk-Pod
    license: http://dev.perl.org/licenses/
    repository: http://sourceforge.net/cvs/?group_id=91459
generated_by: Slaven Rezic
