# http://module-build.sourceforge.net/META-spec.html
name:         Tk-Pod
version:      0.9934
version_from: 
installdirs:  site
requires:
    File::Temp:                    0
    Pod::Simple:                   0
    Tk:                            800.004
recommends:
    Text::English:                 0
    Tk::HistEntry:                 0.4
    Tk::ToolBar:                   0
license: perl
distribution_type: module
resources:
    bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Tk-Pod
    license: http://dev.perl.org/licenses/
