
=head1 NAME

Tk::Pod_usage - How to use the perl/Tk POD browser widget

=head1 DESCRIPTION

To navigate through the documentation one could use

=head2 Hyperlinks

A B<click> on a hyperlink display the corresponding documentation
(if there is any) in the same window. An URL will be displayed in a
web browser using the (non-CPAN) C<WWWBrowser> module (this will
hopefully change).

With <Button-2> the documentation is loaded into a new window
(<Shift-Button-1> works also for those with only a 2 button mouse).

=head2 Selection

A B<double click> tries to load the documentation for the selected
word in the same window.

If the C<Shift> key is simultaneously pressed a new browser window
is opened.

=head2 Key bindings

The L<Tk::Pod::Text> widget is based on the L<Tk::More> widget
inheriting its key bindings.

=head2 Search

Pressing <Key-/> lets you search in the displayed documentation.

=head2 Section Menu

The Section Menu

The 'Section' menu allows to directly jump to the start of a
section in the documentation.

=head2 Action Menu

If you press the right mouse button you get a popup menu
that allows:

=over 4

=item o Back

in history of displayed documentation

=item o Forward

in history of displayed documentation

=item o Reload

the documentation

=item o Edit POD

Start editor with source of the displayed document.

The used editor is selected by the first definition of the environment
variables C<XEDITOR>, C<VISUAL>, C<EDITOR> or as default
F</usr/bin/vi>. If no terminal is available (or on Windows platforms),
the L<ptked|ptked> editor (bundled with Perl/Tk) will be used instead.

See also the menu entries 'File' -E<gt> 'Edit' and 'File' -E<gt> 'Edit
with ptked'.

=item o Search fulltext

Full text search of the POD in the perl library directories. (Note: to
use it one has to install perlindex distribution, see
L<Text::English|Text::English>)

=back

=head1 SEE ALSO

L<tkpod>,
L<perlpod>,
L<pod2man>,
L<pod2text>,
L<pod2html>,
L<Tk::Pod>,
L<Tk::Pod::Text>,
L<Tk::Pod::Tree>,
L<Tk::More>,
L<Tk::Pod::English>,

=head1 KEYWORDS

pod, browser, tk, hypertext

=head1 AUTHOR

Achim Bohnet <F<ach@mpe.mpg.de>>

Current maintainer is Slaven Rezic <F<slaven.rezic@berlin.de>>

Copyright (c) 1997-1998 Achim Bohnet. All rights reserved.  This
documentation is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

